// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(UsedCarsDbContext))]
    [Migration("20181023124820_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.Advertisement", b =>
                {
                    b.Property<Guid>("AdvertisementPK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<int>("EngineTypeFK");

                    b.Property<int>("ModelFK");

                    b.Property<double>("Price");

                    b.Property<DateTime>("ProductionYear");

                    b.Property<int>("TransmissionTypeFK");

                    b.Property<Guid>("UserFK");

                    b.HasKey("AdvertisementPK");

                    b.HasIndex("EngineTypeFK");

                    b.HasIndex("ModelFK");

                    b.HasIndex("TransmissionTypeFK");

                    b.HasIndex("UserFK");

                    b.ToTable("Advertisement");
                });

            modelBuilder.Entity("DAL.Entities.EngineType", b =>
                {
                    b.Property<int>("EngineTypePK")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .HasMaxLength(50);

                    b.HasKey("EngineTypePK");

                    b.ToTable("EngineType");
                });

            modelBuilder.Entity("DAL.Entities.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerPK")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(50);

                    b.HasKey("ManufacturerPK");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("DAL.Entities.Model", b =>
                {
                    b.Property<int>("ModelPK")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ManufacturerFK");

                    b.Property<string>("ModelName")
                        .HasMaxLength(50);

                    b.HasKey("ModelPK");

                    b.HasIndex("ManufacturerFK");

                    b.ToTable("CarModel");
                });

            modelBuilder.Entity("DAL.Entities.Photo", b =>
                {
                    b.Property<int>("PhotoPK")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AdvertisementFK");

                    b.Property<Guid?>("AdvertisementPK");

                    b.Property<string>("PhotoURL");

                    b.HasKey("PhotoPK");

                    b.HasIndex("AdvertisementPK");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("DAL.Entities.TransmissionType", b =>
                {
                    b.Property<int>("TransmissionTypePK")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .HasMaxLength(50);

                    b.HasKey("TransmissionTypePK");

                    b.ToTable("TransmissionType");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserPK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("RegistrationDate");

                    b.HasKey("UserPK");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DAL.Entities.Advertisement", b =>
                {
                    b.HasOne("DAL.Entities.EngineType", "EngineType")
                        .WithMany()
                        .HasForeignKey("EngineTypeFK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelFK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.TransmissionType", "TransmissionType")
                        .WithMany()
                        .HasForeignKey("TransmissionTypeFK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.Model", b =>
                {
                    b.HasOne("DAL.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Entities.Photo", b =>
                {
                    b.HasOne("DAL.Entities.Advertisement", "Advertisement")
                        .WithMany()
                        .HasForeignKey("AdvertisementPK");
                });
#pragma warning restore 612, 618
        }
    }
}
